GolfProgressTracker.Web/Pages/AddRound.cshtml.cs
using GolfProgressTracker.Core.Models;
using GolfProgressTracker.Core.ViewModels;
using GolfProgressTracker.Web.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;

namespace GolfProgressTracker.Web.Pages
{
    public class AddRoundModel(Context context) : PageModel
    {
        private readonly Context _context = context;


        [BindProperty]
        public RoundAndHolesViewModel AddRoundAndHolesViewModel { get; set; } = new();

        private static int HoleNumber = 1;

        public void OnGet()
        {
            HoleNumber = 1;
        }

        public void OnPostAddHole()
        {
            ModelState.Clear();

            AddRoundAndHolesViewModel.Holes.Add(new HoleViewModel
            {
                Number = HoleNumber
            });

            HoleNumber++;
        }

        public void OnPostAddHalfRound()
        {
            ModelState.Clear();

            var holeNum = HoleNumber + 9;

            for (; HoleNumber < holeNum; HoleNumber++)
            {
                AddRoundAndHolesViewModel.Holes.Add(new HoleViewModel
                {
                    Number = HoleNumber
                });
            }
        }

        public void OnPostAddFullRound()
        {
            ModelState.Clear();

            var holeNum = HoleNumber + 18;

            for (; HoleNumber < holeNum; HoleNumber++)
            {
                AddRoundAndHolesViewModel.Holes.Add(new HoleViewModel
                {
                    Number = HoleNumber
                });
            }
        }

        public void OnPostDeleteHole()
        {
            ModelState.Clear();

            if (AddRoundAndHolesViewModel.Holes.Count > 0)
                AddRoundAndHolesViewModel.Holes.RemoveAt(AddRoundAndHolesViewModel.Holes.Count - 1);

            HoleNumber--;
        }

        public void OnPostClearHoles()
        {
            ModelState.Clear();
            AddRoundAndHolesViewModel.Holes.Clear();

            HoleNumber = 1;
        }

        public IActionResult OnPostSubmitRound()
        {
            if (!ModelState.IsValid)
                return Page();

            using var transcation = _context.Database.BeginTransaction();
            
            try
            {
                var newRound = new Round
                {
                    Title = AddRoundAndHolesViewModel.Round.Title,
                    DatePlayed = AddRoundAndHolesViewModel.Round.DatePlayed.ToString("o", CultureInfo.InvariantCulture)
                };

                _context.Round.Add(newRound);
                _context.SaveChanges();

                var roundHoles = AddRoundAndHolesViewModel.Holes
                    .Select(r => new Hole
                    {
                        RoundId = newRound.Id,
                        Number = r.Number,
                        Par = (int)r.Par!,
                        Shots = (int)r.Shots!
                    });

                _context.Hole.AddRange(roundHoles);
                _context.SaveChanges();
                transcation.Commit();

                return Redirect("/Index");
            }
            catch
            {
                TempData["Error"] = "An error occurred saving the new round";
                transcation.Rollback();
                return Page();
            }
        }
    }
}

GolfProgressTracker.Web/Pages/EditRound.cshtml.cs
using GolfProgressTracker.Core.Models;
using GolfProgressTracker.Core.ViewModels;
using GolfProgressTracker.Web.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace GolfProgressTracker.Web.Pages
{
    public class EditRoundModel(Context context) : PageModel
    {
        private readonly Context _context = context;

        [FromRoute]
        public int RoundId { get; set; }

        [BindProperty]
        public RoundAndHolesViewModel EditRoundAndHolesViewModel { get; set; } = null!;

        private static int HoleNumber;

        public IActionResult OnGet()
        {
            var roundAndHoles = _context.Round
                .Include(r => r.Holes)
                .FirstOrDefault(r => r.Id == RoundId);

            if (roundAndHoles is null)
                return Redirect("/");

            EditRoundAndHolesViewModel = ConvertToViewModel(roundAndHoles);

            HoleNumber = EditRoundAndHolesViewModel.Holes
                .Max(h => h.Number) + 1;

            return Page();
        }

        public void OnPostAddHole()
        {
            ModelState.Clear();

            EditRoundAndHolesViewModel.Holes
                .Add(new HoleViewModel
                {
                    Number = HoleNumber
                });

            HoleNumber++;
        }

        public void OnPostDeleteHole()
        {
            ModelState.Clear();

            if (EditRoundAndHolesViewModel.Holes.Count > 0)
                EditRoundAndHolesViewModel.Holes.RemoveAt(EditRoundAndHolesViewModel.Holes.Count - 1);

            HoleNumber--;
        }

        public IActionResult OnPostSaveChanges()
        {
            if (!ModelState.IsValid)
                return Page();

            var roundToUpdate = _context.Round
                .FirstOrDefault(r => r.Id == EditRoundAndHolesViewModel.Round.Id);

            if (roundToUpdate is null)
            {
                TempData["Error"] = "Could not identify round to update";
                return Page();
            }

            _context.Hole
                .RemoveRange(_context.Hole.Where(h => h.RoundId == roundToUpdate.Id));

            using var transcation = _context.Database.BeginTransaction();

            try
            {
                roundToUpdate.Title = EditRoundAndHolesViewModel.Round.Title;
                roundToUpdate.DatePlayed = EditRoundAndHolesViewModel.Round.DatePlayed.ToString("o", CultureInfo.InvariantCulture);

                var newHoles = EditRoundAndHolesViewModel.Holes
                    .Select(h => new Hole
                    {
                        RoundId = roundToUpdate.Id,
                        Number = h.Number,
                        Par = (int)h.Par!,
                        Shots = (int)h.Shots!
                    });

                _context.Hole.AddRange(newHoles);
                _context.SaveChanges();
                transcation.Commit(); 

                return Redirect("/Index");
            }
            catch
            {
                TempData["Error"] = "An error occurred saving the new round";
                transcation.Rollback();
                return Page();
            }
        }

        private static RoundAndHolesViewModel ConvertToViewModel(Round round)
        {
            return new RoundAndHolesViewModel
            {
                Round = new RoundViewModel
                {
                    Id = round.Id,
                    Title = round.Title,
                    DatePlayed = DateOnly.Parse(round.DatePlayed)
                },
                Holes = round.Holes.Select(h => new HoleViewModel
                {
                    Number = h.Number,
                    Par = h.Par,
                    Shots = h.Shots
                }).ToList()
            };
        }
    }
}

GolfProgressTracker.Web/Pages/Index.cshtml.cs
using GolfProgressTracker.Core.ViewModels;
using GolfProgressTracker.Web.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace GolfProgressTracker.Web.Pages;

public class IndexModel(Context context) : PageModel
{
    private readonly Context _context = context;


    public RoundListViewModel RoundListViewModel { get; set; } = new();

    public RoundAndHolesViewModel? RoundAndHolesViewModel { get; set; } = null;

    public void OnGet() 
    {
        RoundListViewModel.RoundViewModels = _context.Round
            .Select(r => new RoundViewModel
            {
                Id = r.Id,
                Title = r.Title,
                DatePlayed = DateOnly.Parse(r.DatePlayed)
            })
            .ToList()
            .OrderByDescending(r => r.DatePlayed)
            .ToList();
    }

    public void OnPostOpenRound([FromQuery] int roundId)
    {
        RoundAndHolesViewModel = _context.Round
            .Include(r => r.Holes)
            .Where(r => r.Id == roundId)
            .Select(r => new RoundAndHolesViewModel
            {
                Round = new RoundViewModel
                {
                    Id = r.Id,
                    Title = r.Title,
                    DatePlayed = DateOnly.Parse(r.DatePlayed),
                },
                Holes = r.Holes.Select(h => new HoleViewModel
                {
                    Number = h.Number,
                    Par = h.Par,
                    Shots = h.Shots
                }).ToList()
            })
            .FirstOrDefault();

        OnGet();
    }

    public void OnPostDeleteRound([FromQuery] int roundId)
    {
        var round = _context.Round
            .Include(r => r.Holes)
            .FirstOrDefault(r => r.Id == roundId);

        if (round is null)
        {
            TempData["Error"] = "Could not identify round to delete";
            OnGet();
            return;
        }

        _context.Round.Remove(round);
        _context.Hole.RemoveRange(round.Holes);        
        _context.SaveChanges();

        TempData["Success"] = "Successfully deleted round";

        OnGet();
    }
}

GolfProgressTracker.Web/Pages/Shared/_AddRoundAndHolesPartial.cshtml
@model GolfProgressTracker.Core.ViewModels.RoundAndHolesViewModel

<form method="post">
    <div class="row mt-2">
        <div class="col-8">
            <div class="form-floating">
                <input asp-for="Round.Title" class="form-control" placeholder=" " />
                <label asp-for="Round.Title">Title</label>
            </div>
            <span asp-validation-for="Round.Title" class="text-danger"></span>
        </div>
        <div class="col-4">
            <div class="form-floating">
                <input asp-for="Round.DatePlayed" type="date" class="form-control" placeholder=" " />
                <label asp-for="Round.DatePlayed">Date Played</label>
            </div>
            <span asp-validation-for="Round.DatePlayed" class="text-danger"></span>
        </div>
    </div>
    <div class="row container mt-3">
        @for (int i = 0; i < Model.Holes.Count; i++)
        {
            var className = i == 0 ? "row" : "row mt-2";

            <div class="@className">
                <div class="col">
                    <div class="form-floating">
                        <input asp-for="Holes[i].Number" class="form-control" placeholder=" " />
                        <label asp-for="Holes[i].Number">Number</label>
                    </div>
                    <span asp-validation-for="Holes[i].Number" class="text-danger"></span>
                </div>
                <div class="col">
                    <div class="form-floating">
                        <input asp-for="Holes[i].Par" class="form-control" placeholder=" " />
                        <label asp-for="Holes[i].Par">Par</label>
                    </div>
                    <span asp-validation-for="Holes[i].Par" class="text-danger"></span>
                </div>
                <div class="col">
                    <div class="form-floating">
                        <input asp-for="Holes[i].Shots" class="form-control" placeholder=" " />
                        <label asp-for="Holes[i].Shots">Shots</label>
                    </div>
                    <span asp-validation-for="Holes[i].Shots" class="text-danger"></span>
                </div>
            </div>
        }
    </div>
    <div class="row mt-3 text-end">
        <div class="col-6"></div>
        <div class="col-2">
            <input type="submit" class="btn btn-primary w-100" asp-page-handler="AddHole" value="Add Hole" />
        </div>
        <div class="col-2">
            <input type="submit" class="btn btn-primary w-100" asp-page-handler="AddHalfRound" value="Add 9 Holes" />
        </div>
        <div class="col-2">
            <input type="submit" class="btn btn-primary w-100" asp-page-handler="AddFullRound" value="Add 18 Holes" />
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-8"></div>
        <div class="col-2">
            <input type="submit" class="btn btn-danger w-100" asp-page-handler="DeleteHole" value="Remove Hole" />
        </div>
        <div class="col-2">
            <input type="submit" class="btn btn-danger w-100" asp-page-handler="ClearHoles" value="Clear Holes" />
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-8"></div>
        <div class="col-4">
            <input type="submit" class="btn btn-success w-100" asp-page-handler="SubmitRound" value="Submit" />
        </div>
    </div>
</form>

GolfProgressTracker.Web/Pages/Shared/_EditRoundAndHolesPartial.cshtml
@model GolfProgressTracker.Core.ViewModels.RoundAndHolesViewModel

<form method="post">
    <input asp-for="Round.Id" hidden />
    <div class="row mt-2">
        <div class="col-8">
            <div class="form-floating">
                <input asp-for="Round.Title" class="form-control" placeholder=" " />
                <label asp-for="Round.Title">Title</label>
            </div>
            <span asp-validation-for="Round.Title" class="text-danger"></span>
        </div>
        <div class="col-4">
            <div class="form-floating">
                <input asp-for="Round.DatePlayed" type="date" class="form-control" placeholder=" " />
                <label asp-for="Round.DatePlayed">Date Played</label>
            </div>
            <span asp-validation-for="Round.DatePlayed" class="text-danger"></span>
        </div>
    </div>
    <div class="row container mt-3">
        @for (int i = 0; i < Model.Holes.Count; i++)
        {
            var className = i == 0 ? "row" : "row mt-2";

            <div class="@className">
                <input asp-for="Holes[i].Id" hidden />
                <div class="col">
                    <div class="form-floating">
                        <input asp-for="Holes[i].Number" class="form-control" placeholder=" " />
                        <label asp-for="Holes[i].Number">Number</label>
                    </div>
                    <span asp-validation-for="Holes[i].Number" class="text-danger"></span>
                </div>
                <div class="col">
                    <div class="form-floating">
                        <input asp-for="Holes[i].Par" class="form-control" placeholder=" " />
                        <label asp-for="Holes[i].Par">Par</label>
                    </div>
                    <span asp-validation-for="Holes[i].Par" class="text-danger"></span>
                </div>
                <div class="col">
                    <div class="form-floating">
                        <input asp-for="Holes[i].Shots" class="form-control" placeholder=" " />
                        <label asp-for="Holes[i].Shots">Shots</label>
                    </div>
                    <span asp-validation-for="Holes[i].Shots" class="text-danger"></span>
                </div>
            </div>
        }
    </div>
    <div class="row mt-3 text-end">
        <div class="col-10"></div>
        <div class="col-2">
            <input type="submit" class="btn btn-primary w-100" asp-page-handler="AddHole" value="Add Hole" />
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-10"></div>
        <div class="col-2">
            <input type="submit" class="btn btn-danger w-100" asp-page-handler="DeleteHole" value="Remove Hole" />
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-8"></div>
        <div class="col-4">
            <input type="submit" class="btn btn-success w-100" asp-page-handler="SaveChanges" value="SaveChanges" />
        </div>
    </div>
</form>

GolfProgressTracker.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Golf Progress Tracker</title>
    <link href="~/GolfFavicon.png" rel="icon" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">

    <style>
        main {
            min-height: 100vh;
            height: fit-content;
            background: gray;
        }
    </style>

    @RenderSection("Styles", required: false)
</head>
<body>
    <main role="main" class="py-3">
        @RenderBody()
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

GolfProgressTracker.Web/Pages/Shared/_RoundListPartial.cshtml
@using System.Globalization
@model GolfProgressTracker.Core.ViewModels.RoundListViewModel

<ul class="list-group">
    @foreach (var round in Model.RoundViewModels)
    {
        <li class="list-group-item container py-3 px-0 round-list-item border border-dark border-2">
            <form method="post">
                <button type="submit" asp-page-handler="OpenRound" asp-route-roundId="@round.Id" class="btn">
                    <div class="row">
                        <div class="col">
                            <strong class="text-light">@round.Title</strong>
                        </div>
                        <div class="col">
                            <span class="text-light">@round.DatePlayed.ToString("D", CultureInfo.CreateSpecificCulture("en-US"))</span>
                        </div>
                    </div>
                </button>
            </form>
        </li>
    }
</ul>

GolfProgressTracker.Web/Pages/Shared/_RoundOverviewPartial.cshtml
@using System.Globalization
@model GolfProgressTracker.Core.ViewModels.RoundAndHolesViewModel

<div class="container text-center">
    <div class="row text-start ms-5 text-light">
        <div class="col">
            <h3>@Model.Round.Title</h3>
        </div>
        <div class="col">
            <h4>@Model.Round.DatePlayed.ToString("D", CultureInfo.CreateSpecificCulture("en-US"))</h4>
        </div>
    </div>
    <div class="row text-start ms-5">
        <div class="col-auto">
            <form method="post">
                <input type="submit" class="btn btn-danger" asp-page-handler="DeleteRound" asp-route-roundId="@Model.Round.Id" value="Delete Round" />
            </form>
        </div>
        <div class="col-auto">
            <a asp-page="EditRound" asp-route-RoundId="@Model.Round.Id" class="btn btn-info">Edit Round</a>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <table class="table table-dark table-striped">
                <thead>
                    <tr>
                        <td><strong>Hole</strong></td>
                        <td><strong>Par</strong></td>
                        <td><strong>Shots</strong></td>
                        <td><strong>Score</strong></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var hole in Model.Holes)
                    {
                        string score;
                        var diff = hole.Shots - hole.Par;
                        if (diff > 0)
                        {
                            score = "+" + diff;
                        }
                        else if (diff < 0)
                        {
                            score = diff + "";
                        }
                        else
                        {
                            score = "Par";
                        }

                        <tr>
                            <td>@hole.Number</td>
                            <td>@hole.Par</td>
                            <td>@hole.Shots</td>
                            <td>@score</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-2 text-light">
        <div class="col container">
            @{
                var par = Model.Holes.Sum(h => h.Par);
                var shots = Model.Holes.Sum(h => h.Shots);
                var totalDiff = shots - par;
                string totalScore;

                if (totalDiff > 0)
                {
                    totalScore = "+" + totalDiff;
                }
                else if (totalDiff < 0)
                {
                    totalScore = totalDiff + "";
                }
                else
                {
                    totalScore = "Par";
                }
            }
            <div class="row">
                <div class="col">
                    <h5>Totals</h5>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Par:</strong>
                </div>
                <div class="col">
                    <span>@par</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Shots:</strong>
                </div>
                <div class="col">
                    <span>@shots</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Score:</strong>
                </div>
                <div class="col">
                    <span>@totalScore</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-3">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Holes:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Par 3:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count(h => h.Par == 3)</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Par 4:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count(h => h.Par == 4)</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Par 5:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count(h => h.Par == 5)</span>
                </div>
                <div class="col-3"></div>
            </div>
        </div>
        <div class="col container">
            <div class="row">
                <div class="col">
                    <h5>Stats</h5>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Eagle:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count(h => h.Shots - h.Par == -2)</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Birdie:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count(h => h.Shots - h.Par == -1)</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Par:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count(h => h.Shots - h.Par == 0)</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Bogey:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count(h => h.Shots - h.Par == 1)</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-1">
                <div class="col-3"></div>
                <div class="col">
                    <strong>Double:</strong>
                </div>
                <div class="col">
                    <span>@Model.Holes.Count(h => h.Shots - h.Par == 2)</span>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row mt-3">
                <div class="col-2"></div>
                <div class="col">
                    <strong>Best Hole:</strong>
                </div>
                <div class="col">
                    @{
                        var bestHole = Model.Holes.MinBy(h => h.Shots - h.Par)!;
                        var bestHolePrefix = "";
                        var bestHoleScore = bestHole.Shots - bestHole.Par;

                        if (bestHoleScore > 0)
                            bestHolePrefix = "+";
                        else if (bestHoleScore < 0)
                            bestHolePrefix = "-";

                        var bestHoleStr = bestHolePrefix + Math.Abs((int)bestHoleScore!);
                    }
                    <span>Hole @(bestHole.Number): @(bestHoleStr == "0" ? "Par" : bestHoleStr)</span>
                </div>
                <div class="col-2"></div>
            </div>
            <div class="row mt-1">
                <div class="col-2"></div>
                <div class="col">
                    <strong>Worst Hole:</strong>
                </div>
                <div class="col">
                    @{
                        var worstHole = Model.Holes.MaxBy(h => h.Shots - h.Par)!;
                        var worstHolePrefix = "";
                        var worstHoleScore = worstHole.Shots - worstHole.Par;

                        if (worstHoleScore > 0)
                            worstHolePrefix = "+";
                        else if (worstHoleScore < 0)
                            worstHolePrefix = "-";

                        var worstHoleStr = worstHolePrefix + Math.Abs((int)worstHoleScore!);
                    }
                    <span>Hole @(worstHole.Number): @(worstHoleStr == "0" ? "Par" : worstHoleStr)</span>
                </div>
                <div class="col-2"></div>
            </div>
        </div>
    </div>
</div>

GolfProgressTracker.Web/Pages/Shared/_StatisticsPartial.cshtml
@model GolfProgressTracker.Core.ViewModels.StatisticsViewModel

<div class="container text-center">
    <div class="row">
        <div class="col-2">
            <strong>Handicap:</strong>
        </div>
        <div class="col-auto">
            <span>@Model.FormatAsString(nameof(Model.Handicap))</span>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-2">
            <strong>Par 3 Score:</strong>
        </div>
        <div class="col-auto">
            <span>@Model.FormatAsString(nameof(Model.AverageParThreeScore))</span>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-2">
            <strong>Par 4 Score:</strong>
        </div>
        <div class="col-auto">
            <span>@Model.FormatAsString(nameof(Model.AverageParFourScore))</span>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-2">
            <strong>Par 5 Score:</strong>
        </div>
        <div class="col-auto">
            <span>@Model.FormatAsString(nameof(Model.AverageParFiveScore))</span>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12">
            <canvas id="ScoreOverTimeChart" width="800" height="400"></canvas>
        </div>
    </div>
</div>